### ISSUE TITLE
EOFError when using multiprocessing

### ISSUE THREAD

**Issue by lsx162534** [Mehooz/vision4leg#12]
Hi:
When I used the command `python starter/ppo_locotransformer.py --config config/rl/static/locotransformer/thin-goal.json --seed 0 --log_dir log --id 0`, I encountered this error:
```
Traceback (most recent call last):
  File "starter/ppo_locotransformer.py", line 123, in <module>
    experiment(args)
  File "starter/ppo_locotransformer.py", line 119, in experiment
    agent.train()
  File "/home/lsx/vision4leg-master/torchrl/algo/rl_algo.py", line 112, in train
    training_epoch_info = self.collector.train_one_epoch()
  File "/home/lsx/vision4leg-master/torchrl/collector/base.py", line 116, in train_one_epoch
    reward = self.take_actions()
  File "/home/lsx/vision4leg-master/torchrl/collector/on_policy.py", line 109, in take_actions
    next_obs, rewards, dones, infos = self.env.step(acts)
  File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/site-packages/gym/core.py", line 384, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
  File "/home/lsx/vision4leg-master/torchrl/env/subproc_vecenv.py", line 139, in step
    results += parent_pipe.recv()
  File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by Christmas-TR** [comment]
> Hi: When I used the command `python starter/ppo_locotransformer.py --config config/rl/static/locotransformer/thin-goal.json --seed 0 --log_dir log --id 0`, I encountered this error:
> 
> ```
> Traceback (most recent call last):
>   File "starter/ppo_locotransformer.py", line 123, in <module>
>     experiment(args)
>   File "starter/ppo_locotransformer.py", line 119, in experiment
>     agent.train()
>   File "/home/lsx/vision4leg-master/torchrl/algo/rl_algo.py", line 112, in train
>     training_epoch_info = self.collector.train_one_epoch()
>   File "/home/lsx/vision4leg-master/torchrl/collector/base.py", line 116, in train_one_epoch
>     reward = self.take_actions()
>   File "/home/lsx/vision4leg-master/torchrl/collector/on_policy.py", line 109, in take_actions
>     next_obs, rewards, dones, infos = self.env.step(acts)
>   File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/site-packages/gym/core.py", line 384, in step
>     observation, reward, terminated, truncated, info = self.env.step(action)
>   File "/home/lsx/vision4leg-master/torchrl/env/subproc_vecenv.py", line 139, in step
>     results += parent_pipe.recv()
>   File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 250, in recv
>     buf = self._recv_bytes()
>   File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
>     buf = self._recv(4)
>   File "/home/lsx/anaconda3/envs/vision4leg/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
>     raise EOFError
> EOFError
> ```

same bug  how to solve this

**Comment by Christmas-TR** [comment]
solved

**Comment by huangjiekaiming** [comment]
Could you tell me how it was solved?

this is my error
"
  File "/home/hj/anaconda3/envs/marl/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/hj/anaconda3/envs/marl/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
"

**Comment by 127161782** [comment]
> same bug how to solve this
Could you tell me how it was solved? I get the same error！
