### ISSUE TITLE
 Request the solution of an error 

### ISSUE THREAD

**Issue by ZYZSD** [Mehooz/vision4leg#13]
Hello,@Mehooz
thanks for your public work,it's pretty interesting.
But there is an error when I run, could you please do me a favour to have a loook?

python starter/ppo_locotransformer.py --config config/rl/static/locotransformer/thin-goal.json --seed 0 --log_dir log --id vision4leg

something wrong went on:

Traceback (most recent call last):
  File "/home/le/hzt/vision4leg-master/starter/ppo_locotransformer.py", line 127, in <module>
    experiment(args)
  File "/home/le/hzt/vision4leg-master/starter/ppo_locotransformer.py", line 123, in experiment
    agent.train()
  File "/home/le/hzt/vision4leg-master/torchrl/algo/rl_algo.py", line 112, in train
    training_epoch_info = self.collector.train_one_epoch()
  File "/home/le/hzt/vision4leg-master/torchrl/collector/base.py", line 116, in train_one_epoch
    reward = self.take_actions()
  File "/home/le/hzt/vision4leg-master/torchrl/collector/on_policy.py", line 95, in take_actions
    out = self.pf.explore(ob_tensor)
  File "/home/le/hzt/vision4leg-master/torchrl/policies/continuous_policy.py", line 86, in explore
    mean, std, log_std = self.forward(x)
  File "/home/le/hzt/vision4leg-master/torchrl/policies/continuous_policy.py", line 487, in forward
    mean = super().forward(x)
  File "/home/le/hzt/vision4leg-master/torchrl/networks/nets.py", line 1011, in forward
    out = att_layer(out)
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 538, in forward
    x = self.norm1(x + self._sa_block(x, src_mask, src_key_padding_mask))
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 546, in _sa_block
    x = self.self_attn(x, x, x,
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 1167, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/le/anaconda3/envs/agt/lib/python3.9/site-packages/torch/nn/functional.py", line 5160, in multi_head_attention_forward
    attn_output_weights = torch.bmm(q_scaled, k.transpose(-2, -1))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

However,I cloudn't modify any code.Cloud you give me some advice about that? Thanks a lot. I am looking forward to your reply~

**Comment by Mehooz** [comment]
Thank you for your notification. It seems that the bug is related to pytorch and CUDA. I can only suggest that you print the sizes of  each input and output, as well as the architecture of the networks. There must be a mismatched pair of shapes of input and NN.
