### ISSUE TITLE
Bug exists when retrieving image

### ISSUE THREAD

**Issue by QuanyiLi** [Mehooz/vision4leg#2]
Hi, @Mehooz 

I find your work pretty interesting and try to train a legged robot with LocoTransformer.

But an error is raised when ```_get_obervation()``` is called, which could be simply reproduced by running ```python env.builder.py``` .

I solved this problem by making the following changes. Is it correct?

![image](https://user-images.githubusercontent.com/24489294/167816505-0e2d3756-1978-421c-950a-0024774332e7.png)

**Comment by Mehooz** [comment]
Hi, what is the error message?

**Comment by Mehooz** [comment]
I recommend you run the project from `starter`. Maybe I forgot to remove some unused test code (which is very old).

**Comment by QuanyiLi** [comment]
Indeed, I run ```starter/ppo_locotransformer.py``` and encounter this bug. The full error message is:

```
E:\conda\envs\vision4leg\python.exe F:/shanghai/vision4leg/starter/ppo_locotransformer.py --config ../config/rl/static/locotransformer/thin-goal.json --seed 0 --log_dir ./ --id 0
C:\Users\78587\AppData\Roaming\Python\Python37\site-packages\pandas\compat\numpy\__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _nlv = LooseVersion(_np_version)
E:\conda\envs\vision4leg\lib\site-packages\setuptools\_distutils\version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
C:\Users\78587\AppData\Roaming\Python\Python37\site-packages\pandas\compat\numpy\function.py:120: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(__version__) >= LooseVersion("1.17.0"):
pybullet build time: Apr 20 2022 13:44:21
2022-05-11 17:44:01.850466: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-05-11 17:44:01.850571: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\framework\dtypes.py:585: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object,
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\framework\dtypes.py:637: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool,
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\framework\tensor_util.py:176: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object: SlowAppendObjectArrayToTensorProto,
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\framework\tensor_util.py:177: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: SlowAppendBoolArrayToTensorProto,
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\autograph\impl\api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
E:\conda\envs\vision4leg\lib\site-packages\tensorflow\python\ops\numpy_ops\np_random.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def randint(low, high=None, size=None, dtype=onp.int):  # pylint: disable=missing-function-docstring
A1MoveGround {'reward_scale': 1, 'obs_norm': True, 'horizon': 1000, 'env_build': {'z_constrain': False, 'motor_control_mode': 'POSITION', 'other_direction_penalty': 0, 'z_penalty': 1, 'clip_num': [0.05, 0.5, 0.5, 0.05, 0.5, 0.5, 0.05, 0.5, 0.5, 0.05, 0.5, 0.5], 'time_step_s': 0.0025, 'num_action_repeat': 16, 'add_last_action_input': True, 'no_displacement': True, 'diagonal_act': True, 'get_image': True, 'depth_image': True, 'depth_norm': True, 'rgbd': False, 'grayscale': False, 'alive_reward': -0.05, 'fall_reward': -20, 'fric_coeff': [1, 0.01, 0.01], 'target_vel': 1.0, 'random_init_range': 1.0, 'domain_randomization': True, 'enable_action_interpolation': False, 'enable_action_filter': False, 'terrain_type': 'random_blocks_sparse_with_subgoal', 'frame_extract': 1, 'subgoal_reward': 100, 'get_image_interval': 1, 'enable_rendering': True}}
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000F04
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 457.20
Vendor = NVIDIA Corporation
Renderer = GeForce RTX 2060/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000000FE4
MotionThreadFunc thread started
E:\conda\envs\vision4leg\lib\site-packages\gym\spaces\box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
F:\shanghai\vision4leg\vision4leg\robots\minitaur.py:211: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(motor_kp, (collections.Sequence, np.ndarray)):
Traceback (most recent call last):
  File "F:/shanghai/vision4leg/starter/ppo_locotransformer.py", line 123, in <module>
    experiment(args)
  File "F:/shanghai/vision4leg/starter/ppo_locotransformer.py", line 35, in experiment
    args.proc_nums
  File "F:\shanghai\vision4leg\vision4leg\get_env.py", line 154, in get_subprocvec_env
    [env_id, env_param])
  File "F:\shanghai\vision4leg\torchrl\env\subproc_vecenv.py", line 61, in __init__
    super().__init__(env_nums, env_funcs, env_args)
  File "F:\shanghai\vision4leg\torchrl\env\vecenv.py", line 25, in __init__
    self.set_up_envs()
  File "F:\shanghai\vision4leg\torchrl\env\subproc_vecenv.py", line 64, in set_up_envs
    self.example_env = self.env_funcs[0](*self.env_args[0])
  File "F:\shanghai\vision4leg\vision4leg\get_env.py", line 72, in get_single_env
    env = make_env(env_id, env_param["env_build"])
  File "F:\shanghai\vision4leg\vision4leg\get_env.py", line 37, in make_env
    env = ENV_DICT[env_name](**env_build_params)
  File "F:\shanghai\vision4leg\vision4leg\envs\env_builder.py", line 334, in build_a1_ground_env
    fixed_delay_observation=fixed_delay_observation
  File "F:\shanghai\vision4leg\vision4leg\envs\locomotion_gym_env_with_rich_information.py", line 223, in __init__
    self.reset()
  File "F:\shanghai\vision4leg\vision4leg\envs\locomotion_gym_env_with_rich_information.py", line 407, in reset
    return self._get_observation(reset=True)
  File "F:\shanghai\vision4leg\vision4leg\envs\locomotion_gym_env_with_rich_information.py", line 620, in _get_observation
    depth = depth_img[np.newaxis, ...]
TypeError: tuple indices must be integers or slices, not tuple
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 0000000000000FE4 exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000F04 exiting
Thread TERMINATED

Process finished with exit code 1
```
It looks like the depth image is represented by a tuple in shape (4096,), instead of 64 x 64. So I simply do a ```np.reshape``` to fix this error.

**Comment by Mehooz** [comment]
Interesting, I just ran on my laptop (Ubuntu 18.04), and `depth_img` is in `(64, 64)`. I suspect the issue is related to the PyBullet rendering module. I saw you set `enable_rendering` to be `True`, but that will not use egl to render and may cause an issue (Like `getCameraImage` might have different return values). Even if you can run with this code, your simulation speed can be much slower than the given setting.

**Comment by Mehooz** [comment]
I suggest we rollback to `enable_rendering` to be `False` and find the solution for how to make egl work on your device.

**Comment by QuanyiLi** [comment]
Actually, I already successfully launch ```ppo_locotransformer.py``` on my headless machine with EGL offscreen rendering, but **with** the modification that I indicated above. Since this modification also works and doesn't change anything if the returned image is in (64, 64), I test this script with the original version without this modification just now. It also works well.

Therefore, I conclude that this error is related to my OS (Windows11). My workflow is to test the training script locally and then launch it on the remote machine. Since EGL is not supported locally, I turn the rendering on and got this issue, which could be solved by the modification above.

Just treat this issue as a corner case and never mind : )

**Comment by QuanyiLi** [comment]
PS: my remote machine is Ubuntu
